### ISSUE TITLE
Theme with Background image applied for site- Not available when site is converted to modern

### ISSUE THREAD

**Issue by InfosysAdmin** [SharePoint/sp-dev-modernization#425] opened 2020-02-05 05:53 UTC
#### Category

[*] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ *] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior
Modern page to get the option of setting a theme with background image for the site

#### Observed Behavior

Classic site has got the Theme with background image. After transformation to modern, theme does not seem to work

**Comment by jansenbe** [comment] 2020-02-05 08:17
Hey @InfosysAdmin , this is by design. Modern pages do not allow you to specify a background image for the page. It's therefore recommended to switch to a modern theme for the sites that you want to modernize. See https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-branding and https://github.com/SharePoint/sp-dev-modernization/tree/dev/Scripts/ModernizeSiteCollection. The latter is a script that does a full site modernization (so not only pages)

**Comment by jansenbe** [comment] 2020-02-07 07:37
Closing this one as it's not about page transformation and the asked question has been answered

**Closed by jansenbe** 2020-02-07 07:37 UTC
Labels: PageTransformationEngine, Pending feedback, question
