### ISSUE TITLE
Enhancement - target non-SitePages library

### ISSUE THREAD

**Issue by TroyHostetter** [SharePoint/sp-dev-modernization#393] opened 2019-12-12 17:38 UTC
It appears "-Library" targets SitePages.  Could we split the -Library option into 2 options .. -SourceLibrary -TargetLibrary.  Specifying neither would assume SitePages.  Specifying SourceLibrary only would target SitePages.  Specifying TargetLibrary only would source SitePages.

**Comment by jansenbe** [comment] 2019-12-12 18:57
The target for modern pages can only be the SitePages library, so I don't think it makes sense to change that as it simply does not work. The use case for -Library is when your wiki or web part pages do not live in the default SitePages library (you can have multiple wiki page libraries and web part pages can be potentially saved in any document library or even the root of the site). 

What would be your use case for having a TargetLibrary option?

**Comment by TroyHostetter** [comment] 2019-12-12 19:38
The main use case is migrations.  Since you can create pages in any Page Library on a source, clients want to maintain consistency, and would rather not force everything into SitePages.  We use the PnP Cmdlet to transform classic pages to modern as part of the migration process.

**Comment by jansenbe** [comment] 2019-12-13 06:53
Hi @TroyHostetter ,

Modern pages **only** work in the sitepages library and there's only **one** site pages library per site. This is by design. So what your client wants is not possible. When you convert pages from other libraries page transformation will automatically create a folder with the original library name and pages are created in there. This will ensure that there are no naming clashes. Also by default the folder structure used in the source library is maintained.

**Comment by TroyHostetter** [comment] 2019-12-16 19:29
Thanks for the clarification @jansenbe !!!

**Comment by jansenbe** [comment] 2019-12-17 07:27
Cool. Closing this issue then

**Closed by jansenbe** 2019-12-17 07:27 UTC
Labels: PageTransformationEngine, Pending feedback, question
