### ISSUE TITLE
Promoted links list web part in modern page loads twice

### ISSUE THREAD

**Issue by RajiVenkat242** [SharePoint/sp-dev-modernization#428] opened 2020-02-12 21:04 UTC
Classic page with promoted link list web part is getting upgraded to  modern. In modern page, we set the Tiles view for that web part. when we open the modern page, web part does not show up the links directly. Instead that web part initially loads the "all items" list view, after few seconds only it redirects the Tiles view. Please advise

**Comment by jansenbe** [comment] 2020-02-14 07:41
Hey @RajiVenkat242 ,

I'm not able to simulate this at my side, switch the modern quick links web part to tiles iso of list works and I don't see a delay in loading. Some questions:

- Can you reproduce the same if you add a new quick links web part to a modern page?
- Can you try this from an in-private session to see if caching somehow is causing this? 

Overall I don't think this is a page transformation bug, but it might be a bug in the quick links web part.

**Comment by RajiVenkat242** [comment] 2020-02-18 16:57
Hi,

Please find below the steps we tried.


  *   Can you reproduce the same if you add a new quick links web part to a modern page?  - This is loading the tiles directly.
  *   Can you try this from an in-private session to see if caching somehow is causing this? - In incognito window also, we observe the below behavior. It loads the “All promoted links” view first, then the Tiles view.
Steps to re produce:


  1.  Add a list web part into modern page and choose any promoted links list.
  2.  Set the tiles view and Save and Publish the page.
  3.  Reload the page

Expected behavior: Tiles view should be loaded.

Actual behavior: First it loads the All promoted links view and then tiles view is coming. There is a delay in loading the tiles view.

This issue is there in the web part, we tried it in a new modern page and the above was the actual behavior.

Please advise.

Regards,
Raji
Ph.No: +1 514 838 3762

**Comment by jansenbe** [comment] 2020-02-18 17:07
So this then seems to be a bug in the OOB web part itself, not in page transformation. Would recommend opening a support case with Microsoft for this.

**Comment by jansenbe** [comment] 2020-02-24 08:03
Hey @RajiVenkat242 , I'm closing this issue as it's not related on how page transformation works, but rather a potential issue in the highlighted content web part rendering. For product issue it's best to follow the regular support channels

**Closed by jansenbe** 2020-02-24 08:03 UTC
Labels: PageTransformationEngine, Pending feedback, question
