### ISSUE TITLE
Content is empty in random cases in Classic page(Eg Previous_PageName) when -TakeSourcePageName switchparameter is used

### ISSUE THREAD

**Issue by PriyankaDevi510** [SharePoint/sp-dev-modernization#229] opened 2019-08-07 07:04 UTC
#### Category

[x] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[x] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior
 
Classic page's content has to be retained after conversion using ConvertTo-PnPClientSidePage -Identity "page.aspx" -AddPageAcceptBanner -TakeSourcePageName

#### Observed Behavior

Classic page is not retaining any data

#### Steps to Reproduce

It is randomly occuring in homepages

**Comment by pkbullock** [comment] 2019-08-08 16:18
HI @PriyankaDevi510 are you able to include the logs for this by adding to your transform script:
```
-LogType File -LogFolder c:\temp
```
This captures any exceptions which might be able to give us some more insight. Also, can you check if this happens on any specific page? Also does it have any closed web parts?

Thanks
Paul

**Comment by PriyankaDevi510** [comment] 2019-08-09 11:21
Hi,
As this issue is raising in random cases, We are unable to get the log file. At the same time, We are unable to reproduce the same issue with the same page as the content was already missed

**Comment by jansenbe** [comment] 2019-08-12 15:08
@PriyankaDevi510 : Can you check if you see any specific things on this page (item level permissions, metadata) and library (approval settings) that's different compared the home pages that work?

**Comment by PriyankaDevi510** [comment] 2019-08-16 05:01
Hi jansenbe,
      On checking,there are no specific differences like item level permissions or metadata between the content missing pages and the other homepages that work.

**Comment by jansenbe** [comment] 2019-08-20 11:33
Hi @PriyankaDevi510,

Found a related issue (https://github.com/SharePoint/PnP-Sites-Core/issues/2052) : can you check that in your case for the failing pages the pages where created programmatically?

**Comment by PriyankaDevi510** [comment] 2019-08-21 12:00
Hey @jansenbe 
Looks like the issue (SharePoint/PnP-Sites-Core#2052) is different from ours. We did not use "AddWebPartToWikiPage" parameter. We used "ConvertTo-PnPClientSidePage -Identity page.aspx -AddPageAcceptBanner -TakeSourcePageName"

**Comment by jansenbe** [comment] 2019-08-21 13:25
Hi @PriyankaDevi510 ,

AddWebPartToWikiPage is not a parameter: what the other issue is saying is that if you've programmatically put the web part on the wiki page in the first place it might get dropped during a copy operation (which we do in the swap pages logic)...so the question is if you understand how that previous page was created?

**Comment by PriyankaDevi510** [comment] 2019-08-30 06:18
Hi @jansenbe 

The previous page has got the web part created using the regular add web part in Page UI. No web part Scripting is used

**Comment by jansenbe** [comment] 2019-09-02 16:44
Thx for the update @PriyankaDevi510, this means we can then rule out the issue I referred to. So the hunt to figure out the root cause continues. Are you able to still repro this?

**Comment by PriyankaDevi510** [comment] 2019-09-03 03:38
No. I am unable to repro this issue. I am just migrating the classic page with this behavior, and testing with other converto-pnpclientsidepage parameters

**Comment by jansenbe** [comment] 2019-09-03 06:13
Let's then close this one again. If you see the error again please keep the log output of the run and if possible run Get-PnPException immediately after the script error.

**Closed by jansenbe** 2019-09-03 06:13 UTC
Labels: PageTransformationEngine, Pending feedback, bug
