### ISSUE TITLE
CEWP Titles missing in webpart zones

### ISSUE THREAD

**Issue by FredrikEkstroem** [SharePoint/sp-dev-modernization#408] opened 2020-01-23 13:33 UTC
#### Category

[ x] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[x ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior
When content editor web parts are in a webpart zone, title should be added in the same way as if the are located in the PublishingPageContent field.

#### Observed Behavior

When placing a web part in the page content field, WebPart title is copied into the target text webpart as long as the chrome type i set accordingly (see #120). However if the web part is placed in a webpart zone it does not look like this is happening.

#### Steps to Reproduce
Source: SP2016 publishing page
Target: SP Online
PNP Version: SharePointPnPPowerShellOnline 3.17.2001.2
Put one CEWP in page content field and one in a webpart zone
 ` ConvertTo-PnPClientSidePage -Identity default.aspx -TakeSourcePageName -PublishingPage -Overwrite -TargetConnection $global:target`

**Comment by jansenbe** [comment] 2020-01-24 16:33
First check doing SPO to SPO shows no issues...next stop, checking SP2016 to SPO

**Comment by FredrikEkstroem** [comment] 2020-01-24 17:36
Thanks. Forgot to mention, custom page layout, SP 2016 in 2013 mode

**Comment by jansenbe** [comment] 2020-01-24 17:53
@FredrikEkstroem : I'm able to repro this, which implies I most likely will able to get this fixed before the next release :-)

**Comment by jansenbe** [comment] 2020-01-27 10:02
Hi @FredrikEkstroem : this problem is fixed and will be part of the February release which will come out on either Feb 14 or Feb 17. The root cause was that for SP2016 and lower we use web service calls to retrieve web part information for publishing pages and that approach did not give us the ChromeState property we expected. I've now added a mapping from the retrieved FrameType (https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ms473016%28v%3doffice.14%29) to ChromeType (https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.webcontrols.webparts.partchrometype?view=netframework-4.8).

**Comment by FredrikEkstroem** [comment] 2020-01-27 10:29
@jansenbe Thanks a lot

**Comment by jansenbe** [comment] 2020-01-27 10:37
I'll close this issue, feel free to create a new one if case you still have issues when testing the Feb bits.

**Closed by jansenbe** 2020-01-27 10:37 UTC
Labels: PageTransformationEngine, bug
