### ISSUE TITLE
Site Slowness- frequently observed

### ISSUE THREAD

**Issue by InfosysAdmin** [SharePoint/sp-dev-modernization#410] opened 2020-01-24 09:53 UTC
After converting the sites to Modern, site slowness is observed frequently

**Comment by pkbullock** [comment] 2020-01-24 10:28
Hi @InfosysAdmin 

As you add content to the portal certain artifacts can slow pages down, such as number of web parts, referenced assets e.g. images. 

I came across a docs article that you might help identify the root cause: https://docs.microsoft.com/en-us/sharepoint/portal-health specifically the Page Diagnostics tool add in for Chrome/New Edge. Part of this is page weight assessment, the rest of the article focuses around optimization, that you might find useful.

Hope this helps.
Paul

**Comment by jansenbe** [comment] 2020-01-27 10:36
Hi @InfosysAdmin ,

@pkbullock already pointed you to the Page Diagnostics tool, which is your best option to assess performance. If overall performance is a problem then please open a support case with Microsoft. The page transformation tool only uses OOB web parts, if these are too slow then again the best approach is to work via Microsoft support.

**Comment by jansenbe** [comment] 2020-02-06 10:22
Hey @InfosysAdmin , I'm closing this issue as it's not something related to page transformation. Hope the above answers provided you the feedback you needed.

**Closed by jansenbe** 2020-02-06 10:22 UTC
Labels: PageTransformationEngine, Pending feedback, question
