### ISSUE TITLE
CEWP with embedded Iframes do not modernize properly

### ISSUE THREAD

**Issue by russgove** [SharePoint/sp-dev-modernization#140] opened 2019-04-30 19:20 UTC
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[x] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[x ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Content Editor webparts that include Iframes in the html should display on modernized version of page.

#### Observed Behavior

The modernized page Looks like this:
![image](https://user-images.githubusercontent.com/2412956/56987301-06b17580-6b5b-11e9-8111-221e7baae86b.png)

The actual text of the CEWP is attached.
[clocks.txt](https://github.com/SharePoint/sp-dev-modernization/files/3132771/clocks.txt)

Not sure if its even possible to include an iframe in a modern text webpart

**Comment by jansenbe** [comment] 2019-04-30 21:11
Hey @russgove ,

If an iframe is used for embedding a video than it's modernized...but only if not inside a table. In this case, the iframe is inside a table and modern text editor does not support rich content inside a table. Second thing is that this is not a video embed...so what you see is by design. In this case it's recommended to manually update this page and use the modern clock web part to show the time for the respective places.

I'm closing this question, feel free to re-open if you need more info.

**Closed by jansenbe** 2019-04-30 21:11 UTC
Labels: question
