### ISSUE TITLE
Recurring events in Calendar list is not appearing in Events web part

### ISSUE THREAD

**Issue by RajiVenkat242** [SharePoint/sp-dev-modernization#271] opened 2019-09-16 13:49 UTC
When we replace the calendar web part to Events web part in modern Page, recurring events are not coming in the Events web part. 

Steps:
Create calendar web part & add recurring events
Create modern page and add the events web part .
Change the web part to fetch events from Calendar list

**Comment by jansenbe** [comment] 2019-09-16 16:19
Hey @RajiVenkat242,

The modern events web part does not support recurring events. See https://techcommunity.microsoft.com/t5/SharePoint/Modern-Page-Events-Web-Part-missing-reoccurring-events/m-p/207009 for some discussion on that.

Page transformation tech can't solve this for you unless you replace the 1st party events web part with a custom 3rd party events web part at transformation time.

**Comment by jansenbe** [comment] 2019-09-17 09:15
Closing this one as this is by design. If you take the approach to use a third party events web part and encounter issues configuring that then feel free to create a new issue to help with that.

**Closed by jansenbe** 2019-09-17 09:15 UTC
Labels: Pending feedback

**Comment by RajiVenkat242** [comment] 2019-09-17 11:42
Thank you. Could you please let me know if there are any other option on how to add a calendar list view in Site page.

**Comment by jansenbe** [comment] 2019-09-18 06:32
Currently for modern pages there's only the events webpart...alternative is a custom developed calendar web part. Would recommend checking user voice and vote for this: https://sharepoint.uservoice.com/forums/329214-sites-and-collaboration/suggestions/19329577-modern-calendars looks to be about modern calendar
