### ISSUE TITLE
WhiteSpaces in Modernized Page

### ISSUE THREAD

**Issue by mmohamedbasith** [SharePoint/sp-dev-modernization#435] opened 2020-02-21 15:03 UTC
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[X] Page Transformation: Error during the use of page transformation from .Net
[X] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Modernized the classic page as modern page. Clicked on 'Edit' Button and format of the text and paragraph remains intact.

#### Observed Behavior

Modernized the classic page as modern page. Clicked on 'Edit' Button and there is lot of whitespaces generated between the paragraphs . 

#### Steps to Reproduce

1.Modernize the Classic to Modern page using .NET/Powershell.
2.Edit any converted modern page.
3.See the page format .Lot of whitespaces gets generated between paragraphs

#### Submission Guidelines

_Delete this section after reading_

- All suggestions or bugs are welcome, please let us know what's on your mind.
- If you checked the **"Page Transformation: Error during the setup/use of the Page Transformation UI solution"** checkbox then please provide:
  - The output of the following 2 PnP PowerShell statements: `Get-PnPStorageEntity` and `Get-PnPTenantServicePrincipalPermissionGrants`
  - The errors listed inside the browser's developer tools window (F12), if possible tested with Chrome as browser
  - The versions of the **sharepointpnp-pagetransformation-client-solution** and **sharepointpnp-pagetransformation-central-solution** solutions in your SharePoint tenant app catalog
- If you checked the **"Page Transformation: Error during the use of page transformation from PnP PowerShell"** checkbox then please provide:
  - The output you see in your PowerShell session
  - The output generated by calling `Get-PnPException`
  - The PnP PowerShell version. Run `get-module -Name SharePointPnPPowerShellOnline` and copy the version info
- If you checked the **"Page Transformation: Error during the use of page transformation from .Net"** checkbox then please provide:
  - The exact error message you get
  - The stack trace of the error
  - The version of the **SharePointPnP.Modernization.Framework.dll** assembly

Thanks for your contribution! Sharing is caring.

**Comment by jansenbe** [comment] 2020-02-23 19:03
Hey @mmohamedbasith ,

Can you provide more details on the source page that you're transforming, ideally share it's html. Web parts on modern pages are having more whitespace between them by design, when modernizing text content then having empty paragraph tags for example can cause additional whitespace. There's a known issue with header tags (H1-H5) getting embedded in a paragraph tag by the modern page API in the PnP Sites core library (the one we're using), but that should not generate a lot of additional whitespace.

**Comment by jansenbe** [comment] 2020-03-06 17:27
Closing per no additional feedback.

**Closed by jansenbe** 2020-03-06 17:27 UTC
Labels: PageTransformationEngine, Pending feedback, question
