### ISSUE TITLE
ConvertTo-PnPClientSidePage (for multiple pages) in conjunction with Save-PnPClientSidePageConversionLog generates wrong log file

### ISSUE THREAD

**Issue by PRusakPL** [SharePoint/sp-dev-modernization#430] opened 2020-02-17 07:49 UTC
#### Category
[x] Bug

#### Problem Area
[x] Page Transformation: Error during the use of page transformation from PnP PowerShell

#### Expected or Desired Behavior

When using command ConvertTo-PnPClientSidePage (with switches -LogType File and -LogSkipFlush) in conjunction with  Save-PnPClientSidePageConversionLog created log file should include information about all transformed pages.

#### Observed Behavior

Created log file contains information about last processed page only.

#### Steps to Reproduce

Use 3.18.2002.0 (February 2020) of SharePointPnPPowershellOnline module (bug was introduced in this version exactly)
Call ConvertTo-PnPClientSidePage (for multiple pages - using [LogSkipFlush] for every page). Call Save-PnPClientSidePageConversionLog after all conversions.

**Comment by jansenbe** [comment] 2020-02-17 11:58
This is a regression due to merging https://github.com/SharePoint/sp-dev-modernization/pull/415. I'll have a look at how to solve both cases and will get this fixed for the next release.

**Comment by PRusakPL** [comment] 2020-02-17 12:53
Thank you Bert. 
Awesome work with these tools. 
Regressions happen - normal thing.

**Comment by jansenbe** [comment] 2020-02-17 13:55
Thanks. If the meantime logging is critical in your case you can revert back the January release.

**Comment by jansenbe** [comment] 2020-02-19 08:06
@PRusakPL : I've reverted #415. This fix will be part of the March release (first week of March). Will close this issue now, if things still don't work with the March release then please let us know.

**Closed by jansenbe** 2020-02-19 08:06 UTC
Labels: PageTransformationEngine, bug
