### ISSUE TITLE
Publishing page conversion which contain certain table information or formatting

### ISSUE THREAD

**Issue by berryst2** [SharePoint/sp-dev-modernization#114] opened 2019-04-12 02:00 UTC
[ ] Bug

#### Problem Area

[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
We have classic publishing pages whose body column (e.g.: PublishingPageContent) contains table and we tried to map this as a modern webpart (SharePointPnP.Modernization.WikiTextPart) in the custom page layout mapping file, below is the snippet from the custom mapping that we used

```
<Field Name="PublishingPageContent" TargetWebPart="SharePointPnP.Modernization.WikiTextPart" Row="3" Column="1">
          <Property Name="Text" Type="string"  Functions="TextCleanup({PublishingPageContent})"/>          
        </Field>
```

#### Expected or Desired Behavior

We're expecting the transformation engine would be able to translate pages which contain tables without any error

#### Observed Behavior

When we transform publishing pages which contain table, we got the following error message 
```
ConvertTo-PnPClientSidePage : Exception has been thrown by the target of an invocation.
At line:1 char:27
+ ... odernPage = ConvertTo-PnPClientSidePage -Identity $pages[11].FieldVal ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [ConvertTo-PnPClientSidePage], TargetInvocationException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.ClientSidePages.ConvertToClientSidePage
```
 

#### Steps to Reproduce

Create  a new classic publishing page and insert table(s) and populate the table with some information and do some formatting on the table. 

sample tables

![table](https://user-images.githubusercontent.com/23225850/56006804-7e456f00-5d2a-11e9-9244-57008ea7de34.png)

![table2](https://user-images.githubusercontent.com/23225850/56006864-ab921d00-5d2a-11e9-8537-803181c70e74.png)

Run the conversion for the classic publishing page and you might get the error. 
If you do not get the error, the table that was created might not have additional custom formatting, complexity or information. 

#### Submission Guidelines
  - The output generated by calling `Get-PnPException`
```
Message          : Exception has been thrown by the target of an invocation.
Stacktrace       :    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
                      at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
                      at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
                      at SharePointPnP.Modernization.Framework.Functions.BaseFunctionProcessor.ExecuteMethod(Object functionClassInstance, FunctionDefinition functionDefinition, MethodInfo 
                   methodInfo)
                      at SharePointPnP.Modernization.Framework.Functions.FunctionProcessor.ExecutePropertyFunctions(String[] functionsToProcess, WebPart webPartData, WebPartEntity webPart, 
                   Property property)
                      at SharePointPnP.Modernization.Framework.Functions.FunctionProcessor.Process(WebPart& webPartData, WebPartEntity webPart)
                      at SharePointPnP.Modernization.Framework.Transform.ContentTransformator.Transform(List`1 webParts)
                      at SharePointPnP.Modernization.Framework.Publishing.PublishingPageTransformator.Transform(PublishingPageTransformationInformation 
                   publishingPageTransformationInformation)
                      at SharePointPnP.PowerShell.Commands.ClientSidePages.ConvertToClientSidePage.ExecuteCmdlet()
                      at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()
ScriptLineNumber : 1
```
  - The PnP PowerShell version. Run `get-module -Name SharePointPnPPowerShellOnline` and copy the version info
3.8.1904.0

**Comment by pkbullock** [comment] 2019-04-12 07:13
Hi @berryst2 

Is it possible to post the HTML for the table? We can look to reproduce the issue exactly. 

Paul

**Comment by jansenbe** [comment] 2019-04-12 08:39
Hi @berryst2,

Thx for reporting this. Can you try to change the mapping as follows:

```XML
<Field Name="PublishingPageContent" TargetWebPart="SharePointPnP.Modernization.WikiTextPart" Row="3" Column="1">
          <Property Name="Text" Type="string"  Functions=""/>          
        </Field>
```

Since you map to a WikiTextPart all the html parsing and cleaning is included automatically. If the above still gives an error then please paste the raw html content of the field.

**Comment by berryst2** [comment] 2019-04-16 01:40
Hi Bert,
thanks for the follow-up.
please find below for the copy my htmlbody. i'll ask the customer that i was working with to copy their version of the table as well

```
<p>​​​​Page COntent Body Here too...<br/></p>
<table cellspacing="0" width="100%" class="ms-rteTable-default">
   <tbody>
      <tr class="ms-rteTableHeaderRow-default">
         <th class="ms-rteTableHeaderEvenCol-default" rowspan="1" colspan="1" style="width: 33.3333%;">​column 1<br/><br/></th>
         <th class="ms-rteTableHeaderOddCol-default" rowspan="1" colspan="1" style="width: 33.3333%;">​<span style="color: #777777;">column 12</span><br/></th>
         <th class="ms-rteTableHeaderEvenCol-default" rowspan="1" colspan="1" style="width: 33.3333%;">​<br/><span style="color: #777777;">column 1</span>​<br/></th>
      </tr>
      <tr class="ms-rteTableOddRow-default">
         <td class="ms-rteTableEvenCol-default">​</td>
         <td class="ms-rteTableOddCol-default">​</td>
         <td class="ms-rteTableEvenCol-default">​<br/></td>
      </tr>
      <tr class="ms-rteTableEvenRow-default">
         <td class="ms-rteTableEvenCol-default">​</td>
         <td class="ms-rteTableOddCol-default">​</td>
         <td class="ms-rteTableEvenCol-default">​<br/></td>
      </tr>
   </tbody>
</table>
<p>
   <br/>
</p>
<table cellspacing="0" width="100%" class="ms-rteTable-6">
   <tbody>
      <tr class="ms-rteTableHeaderRow-6">
         <th class="ms-rteTableHeaderFirstCol-6" rowspan="1" colspan="1" style="width: 33.3333%;">​​​Column1<br/></th>
         <th class="ms-rteTableHeaderOddCol-6" rowspan="1" colspan="1" style="width: 33.3333%;">Column2<br/></th>
         <th class="ms-rteTableHeaderLastCol-6" rowspan="1" colspan="1" style="width: 33.3333%;">Column3<br/></th>
      </tr>
      <tr class="ms-rteTableOddRow-6">
         <th class="ms-rteTableFirstCol-6" rowspan="1" colspan="1">​
            <p>ge COntent Body Here too...<br/></p>​<br/>
            <table cellspacing="0" width="100%" class="ms-rteTable-default">
               <tbody>
                  <tr class="ms-rteTableHeaderRow-default">
                  </tr>
               </tbody>
            </table>
            <br/>
         </th>
         <td class="ms-rteTableOddCol-6">​<br/></td>
         <td class="ms-rteTableLastCol-6" rowspan="1" colspan="1">​<br/><br/></td>
      </tr>
      <tr class="ms-rteTableEvenRow-6">
         <th class="ms-rteTableFirstCol-6" rowspan="1" colspan="1">​asd<br/></th>
         <td class="ms-rteTableOddCol-6" rowspan="1">​asdasdasdasdasdasd<br/><br/></td>
         <td class="ms-rteTableLastCol-6" rowspan="1" colspan="1">​<br/>adasasd<br/></td>
      </tr>
      <tr class="ms-rteTableOddRow-6">
         <th class="ms-rteTableFirstCol-6" rowspan="1" colspan="1">​<br/>asdasdasdasdasdasd<br/></th>
         <td class="ms-rteTableOddCol-6" rowspan="1">​asasd<br/></td>
         <td class="ms-rteTableLastCol-6" rowspan="1" colspan="1">​<br/>asdasd<br/></td>
      </tr>
      <tr class="ms-rteTableFooterRow-6">
         <th class="ms-rteTableFooterFirstCol-6" rowspan="1" colspan="1">​asdasd<br/></th>
         <td class="ms-rteTableFooterOddCol-6" rowspan="1">​asdasd<br/></td>
         <td class="ms-rteTableFooterLastCol-6" rowspan="1" colspan="1">​asdasd<br/></td>
      </tr>
   </tbody>
</table>
<p>
   <br/>
   <br/>
</p>
```

**Comment by jansenbe** [comment] 2019-04-16 07:09
Hi @berryst2,

The table structure shows TH in each TR, which is something I fixed in #118. Besides that I think this should work fine assuming you configure the field mapping as shown below:

```xml
<Field Name="PublishingPageContent" TargetWebPart="SharePointPnP.Modernization.WikiTextPart" Row="3" Column="1">
          <Property Name="Text" Type="string"  Functions=""/>          
</Field>
```

Would you be able to test with a development build?

**Comment by berryst2** [comment] 2019-04-16 22:07
Hi Bert,
I just tried and it still using the following version 3.8.1904.0 and it failed..following is the exception
Get-PnPException..how do we get the dev.build..sorry been very busy working on another engagement...


Message          : Exception has been thrown by the target of an invocation.
Stacktrace       :    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
                      at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
                      at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
                      at SharePointPnP.Modernization.Framework.Functions.BaseFunctionProcessor.ExecuteMethod(Object functionClassInstance, FunctionDefinition functionDefinition, MethodInfo 
                   methodInfo)
                      at SharePointPnP.Modernization.Framework.Functions.FunctionProcessor.ExecutePropertyFunctions(String[] functionsToProcess, WebPart webPartData, WebPartEntity webPart, 
                   Property property)
                      at SharePointPnP.Modernization.Framework.Functions.FunctionProcessor.Process(WebPart& webPartData, WebPartEntity webPart)
                      at SharePointPnP.Modernization.Framework.Transform.ContentTransformator.Transform(List`1 webParts)
                      at SharePointPnP.Modernization.Framework.Publishing.PublishingPageTransformator.Transform(PublishingPageTransformationInformation 
                   publishingPageTransformationInformation)
                      at SharePointPnP.PowerShell.Commands.ClientSidePages.ConvertToClientSidePage.ExecuteCmdlet()
                      at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()

**Comment by berryst2** [comment] 2019-04-16 22:08
here's another content of the HTML table that we've encountered error

<table class="data " cellspacing="0" cellpadding="4">
   <thead>
      <tr>
         <th>Entity</th> 
         <th>Value1</th> 
         <th>Value2</th> 
         <th>
         </th>
      </tr>
   </thead> 
   <tbody>
   </tbody> 
   <tbody>
      <tr>
         <td>Entity1</td> 
         <td>&gt;$250,000</td> 
         <td>&gt;$100,000</td> 
         <td>
         </td>
      </tr> 
      <tr>
         <td>Entity2</td> 
         <td>$500,000</td> 
         <td>$250,000</td> 
         <td>
         </td>
      </tr> 
      <tr>
         <td>Entity3</td> 
         <td>$250,000</td> 
         <td>$100,000</td> 
         <td>
         </td>
      </tr> 
      <tr>
         <td>Entity4</td> 
         <td>$0</td> 
         <td>$0</td> 
         <td>
         </td>
      </tr> 
      <tr>
         <td>Entity5 - Subentity </td> 
         <td>$0</td> 
         <td>$0</td> 
         <td>
         </td>
      </tr> 
      <tr>
         <td>Entity Six</td> 
         <td>$0</td> 
         <td>$0</td> 
         <td>
         </td>
      </tr> 
      <tr>
         <td>Entity Seven</td> 
         <td>$0</td> 
         <td>$0</td> 
         <td>
         </td>
      </tr> 
      <tr>
         <td>Entity Eight (Geo1, Geo2, Geo3, Geo4, Geo5, Geo6, Geo7, Geo8)</td> 
         <td>$0</td> 
         <td>$0</td> 
         <td>
         </td>
      </tr> 
      <tr>
         <td>Entity Nine (Geo1, Geo2, GeoThree, GeoFour, Geo5, Geo6)</td> 
         <td>$0</td> 
         <td>$0</td> 
         <td>
         </td>
      </tr> 
      <tr>
         <td>Entity Ten (Geo1, Geo2, Geo3, Geo4, Geo5)</td> 
         <td>$0</td> 
         <td>$0</td> 
         <td>
         </td>
      </tr>
   </tbody>
</table>

**Comment by jansenbe** [comment] 2019-04-16 22:17
@berryst2 : Building your own custom PS is slightly complex due to the way how things are setup. To test this I would recommend using VS 2017 with the latest source. If you setup the app.config of the test project  to point to your source and target site you can then use this sample test to run the transformation for a single page: https://github.com/SharePoint/sp-dev-modernization/blob/dev/Tools/SharePoint.Modernization/SharePointPnP.Modernization.Framework.Tests/Transform/Publishing/PublishingPageTests.cs#L37. This will then also allow you to debug the code in case you would want to do that.

For the HTML table shared in your last post: can you past the actual source HTML as well?

**Comment by jansenbe** [comment] 2019-04-24 02:38
@berryst2 : I've yesterday fixed an issue with $0 inside html content as it caused an exception during regex based token parsing...with that and the other table fixes I'm quite sure your issues should be fixed as well. Not sure if you have the option to test the dev build?

**Comment by jansenbe** [comment] 2019-04-29 08:23
Hi @berryst2,

I'll close this issue now. Feel free to re-open it if you can reproduce the problem with the upcoming May version. If so please also share the actual page html.

**Closed by jansenbe** 2019-04-29 08:23 UTC
Labels: PageTransformationEngine, Pending feedback
