### ISSUE TITLE
Yammer conversations web part - Backspace/Delete key is not working

### ISSUE THREAD

**Issue by RajiVenkat242** [SharePoint/sp-dev-modernization#308] opened 2019-10-02 04:04 UTC
When trying to reply to any of the conversation in the yammer web part in modern site page. In the Reply text box, backspace/ delete key is not working. Please find the attachment for the same. 

But we can use these keys in yammer page, but not in yammer web part reply text box.
![Yammer](https://user-images.githubusercontent.com/54291136/66017307-db5ef800-e4f7-11e9-8d50-a9e2b13b9ad9.png)

Steps to reproduce:
add a yammer conversation web part to any site page
Click on 'Reply' to any of the conversation
Type any comment and use Backspace/Delete key - not workin.

**Comment by jansenbe** [comment] 2019-10-02 08:40
Hi @RajiVenkat242 ,

I assume you've updated the webpartmapping.xml file for this. Can you share the updated part of that file?

Also, if you manually configure the Yammer web part on a page, does it then show the same issue? We need to identify whether the issue is a Yammer web part issue or whether it's due to the Yammer web part configuration you're pushing in.

**Comment by RajiVenkat242** [comment] 2019-10-02 12:40
HI,

Yes, we are getting this issue when we add the yammer web part manually in a modern page.

**Comment by jansenbe** [comment] 2019-10-02 13:29
So this is not an issue related to the page transformation engine. I'll be starting an internal thread on this and will point folks to this issue.

**Comment by jansenbe** [comment] 2019-10-02 18:27
Hi @RajiVenkat242,

Got feedback this is a known issue and it's being worked on. Will be closing this issue for now as it's not something we can fix here + there's work on going to get it fixed.

**Closed by jansenbe** 2019-10-02 18:27 UTC
Labels: Pending feedback, question
